---
- name: install ycsb 
  hosts: "{{ INPUT_HOST }}" 
  #become: True
  gather_facts: yes

  vars:
    root_dir: "{{ hostvars[inventory_hostname].remote_dir }}"
    ycsb_dir: "{{ root_dir }}/ycsb-0.17.0"
    packages:
    - python

  tasks:
    - name: install apt packages
      apt: 
        name: "{{ packages }}"
    
    - name: create dir
      file:
        path: "{{ root_dir }}"
        state: directory 
        mode: 0775
    
    - name: copy ycsb directory
      copy:
        src: "{{ ycsb_dir }}"
        dest: "{{ root_dir }}"
